name: Run Koncur nightly (Release 0.9)

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  run-nightly:
    uses: konveyor/ci/.github/workflows/nightly-koncur.yaml@main
    with:
      branch: release-0.9
    secrets: inherit

